### ISSUE TITLE
Website not live yet

### ISSUE THREAD

**Issue by TobiEnveda** [idslme/IDSL.CSA#1]
Website: **https://csa.idsl.me** is not active yet?
Also the info has some weird characters? 
````
> library(IDSL.CSA)
> IDSL.CSA_workflow("Address of the CSA parameter spreadsheet")

[0;92mInitiated testing the IDSL.CSA workflow spreadsheet consistency![0m
[0;91mThe IDSL.CSA workflow spreadsheet not found! It should be an Excel file with .xlsx extention![0m
[0;91mPlease visit    https://csa.idsl.me    for instructions!!![0m
>
````

**Comment by sajfb** [comment]
The **website** is down and the communication message will no longer be included in future releases.

You can download [**IDSL.CSA parameter spreadsheet**](https://raw.githubusercontent.com/idslme/IDSL.CSA/main/CSA_parameters.xlsx). and fill it with the required processing parameters. When you are ready to run the analysis, you can provide the address of the CSA parameter spreadsheet on your local drive as the input to the `IDSL.CSA_workflow` function. The packages will then read in the parameter values from the spreadsheet and use them in the analysis.

Those **weird characters** are actually used to adjust R command colors to highlight error messages, and they have worked fine with Ubuntu and Windows systems.
```
cat("\033[92mEverything is OK!!\033[0m\n")
cat("\033[91mError: Something went wrong!\033[0m\n")
```
